# Generated by Django 3.2 on 2021-04-22 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('account_number', models.CharField(default='286105482590', editable=False, max_length=10, unique=True)),
                ('account_balance', models.FloatField(default=0.0)),
                ('registration_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('transaction_id', models.CharField(default=uuid.UUID('21b45e0a-f153-4627-99ed-d980c22aefc8'), max_length=16)),
                ('transaction_type', models.CharField(choices=[('credit', 'DEPOSIT'), ('debit', 'WITHDRAW'), ('', None)], default=None, max_length=6)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 4, 22, 8, 40, 4, 874990))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.user')),
            ],
        ),
    ]
